[server]
port = 5000
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
baseUrlPath = ""
headless = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
